apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: tgindia
spec:
  replicas: 4
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
     labels:
       app: tomcat
    spec:
     imagePullSecrets:
       - name: dhpasswd
     containers:
       - name: tomcat
         image: rahulpatelabc/newtomcat:BUILD_NUMBER
         ports:
          - containerPort: 8080
      
